server:
  port: 8083
sidpik:
  environment: PROD
spring:
  application:
    name: sportify-backend-api
  data:
    mongodb:
      auto-index-creation: false
      uri: mongodb://mongo:yVpOervNTOrbdJOHoejtZvYAYwMLQHBA@viaduct.proxy.rlwy.net:10124/test